"""empty message

Revision ID: 84307ad56c2e
Revises: 
Create Date: 2019-12-21 17:11:01.520116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84307ad56c2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('chinese', sa.Float(), nullable=True),
    sa.Column('math', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
