"""empty message

Revision ID: dbe18fe16382
Revises: 84307ad56c2e
Create Date: 2019-12-21 17:25:37.218870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe18fe16382'
down_revision = '84307ad56c2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_title'), 'article', ['title'], unique=False)
    op.create_index(op.f('ix_student_name'), 'student', ['name'], unique=True)
    op.drop_index('name', table_name='student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'student', ['name'], unique=True)
    op.drop_index(op.f('ix_student_name'), table_name='student')
    op.drop_index(op.f('ix_article_title'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
